name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test & Lint
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      # Caching go modules to speed up the run
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run go fmt
        run: make fmt

      - name: Run go vet
        run: make vet

      - name: Run golint
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get -u golang.org/x/lint/golint
          make lint

      - name: Run go test
        run: make test
